- hosts: linux
  tasks:
  - name: print output
    command: echo " i am in ansible training"
    register: cmdoutput
  - debug: msg="standard output={{cmdoutput.stdout}}"
  - debug: msg="standart error={{cmdoutput.stderr}}"
